(function(){
  if(!document.getElementById('richflow-community-style')){
    const style=document.createElement('style');
    style.id='richflow-community-style';
    document.head.appendChild(style);
    fetch('community.css').then(response=>response.text()).then(css=>{style.textContent=css;}).catch(()=>{});
  }
  const STORE='richflow:community:posts:v1';
  const LIKES='richflow:community:likes:v1';
  const now=Date.now();
  const seeds=[
    {id:'s1',market:'kr',entityType:'stock',entityId:'005930',ticker:'005930',stockName:'삼성전자',sector:'기술',stance:'positive',author:'반도체체크',text:'HBM 인증 뉴스보다 다음 분기 메모리 믹스와 영업이익률을 먼저 봐야 한다고 생각합니다.',source:'https://dart.fss.or.kr/',createdAt:now-12*60000,likes:42,replies:8},
    {id:'s2',market:'kr',entityType:'research',entityId:'000660',ticker:'000660',stockName:'SK하이닉스',sector:'기술',stance:'neutral',author:'신중한개미',text:'업황은 좋지만 기대가 많이 반영된 구간입니다. 고객 집중도와 설비투자 증가 속도를 함께 확인해야 합니다.',source:'',createdAt:now-38*60000,likes:27,replies:5},
    {id:'s3',market:'kr',entityType:'stock',entityId:'005380',ticker:'005380',stockName:'현대차',sector:'경기소비재',stance:'positive',author:'장기복리',text:'환율 효과를 제외해도 북미 ASP가 유지되는지가 핵심입니다. 주주환원은 하방을 지지할 수 있어 보입니다.',source:'',createdAt:now-95*60000,likes:31,replies:4},
    {id:'s4',market:'kr',entityType:'stock',entityId:'035420',ticker:'035420',stockName:'NAVER',sector:'커뮤니케이션',stance:'negative',author:'숫자먼저',text:'AI 서비스 트래픽이 실제 광고·커머스 매출로 연결되는 증거가 아직 부족합니다.',source:'',createdAt:now-4*3600000,likes:19,replies:7},
    {id:'s5',market:'us',entityType:'article',entityId:'nvda-fy27-q1',ticker:'NVDA',stockName:'NVIDIA',sector:'기술',stance:'positive',author:'AI인프라',text:'신제품 전환기에 총마진이 흔들려도 데이터센터 수요와 공급 가시성이 유지되는지가 더 중요합니다.',source:'https://investor.nvidia.com/',createdAt:now-9*60000,likes:64,replies:12},
    {id:'s6',market:'us',entityType:'stock',entityId:'MSFT',ticker:'MSFT',stockName:'Microsoft',sector:'기술',stance:'neutral',author:'클라우드추적',text:'Azure 성장률만 보지 말고 AI 인프라 투자 대비 잉여현금흐름 회수 기간을 같이 봐야 합니다.',source:'',createdAt:now-27*60000,likes:38,replies:9},
    {id:'s7',market:'us',entityType:'stock',entityId:'TSLA',ticker:'TSLA',stockName:'Tesla',sector:'경기소비재',stance:'negative',author:'밸류헌터',text:'자동차 마진과 신규 사업 기대를 분리해서 봐야 합니다. 현재 가격에는 실행 전 기대가 너무 많이 섞여 있습니다.',source:'',createdAt:now-70*60000,likes:51,replies:23},
    {id:'s8',market:'us',entityType:'research',entityId:'AAPL',ticker:'AAPL',stockName:'Apple',sector:'기술',stance:'positive',author:'현금흐름주의',text:'서비스 매출과 설치 기반의 질이 유지된다면 단기 제품 사이클 둔화는 감당할 수 있다고 봅니다.',source:'',createdAt:now-3*3600000,likes:22,replies:3}
  ];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const safeUrl=v=>/^https?:\/\//i.test(String(v||''))?String(v):'';
  const read=()=>{try{const value=JSON.parse(localStorage.getItem(STORE));if(Array.isArray(value))return value;}catch(e){} localStorage.setItem(STORE,JSON.stringify(seeds));return [...seeds];};
  const write=posts=>localStorage.setItem(STORE,JSON.stringify(posts));
  const liked=()=>{try{return new Set(JSON.parse(localStorage.getItem(LIKES))||[]);}catch(e){return new Set;}};
  const stanceLabel={positive:'긍정',neutral:'중립',negative:'부정'};
  const typeLabel={stock:'종목',article:'아티클',research:'리서치',general:'자유토론'};
  const ago=t=>{const m=Math.max(1,Math.floor((Date.now()-t)/60000));return m<60?m+'분 전':m<1440?Math.floor(m/60)+'시간 전':Math.floor(m/1440)+'일 전';};
  const targetUrl=p=>p.entityType==='general'?'community.html':p.entityType==='article'
    ?'article.html?m='+p.market+'&id='+encodeURIComponent(p.entityId)
    :p.entityType==='research'
      ?'research-request.html?m='+p.market+'&code='+encodeURIComponent(p.ticker)
      :p.market==='us'?'stock-us.html?t='+encodeURIComponent(p.ticker):'stock.html?code='+encodeURIComponent(p.ticker);
  const related=(post,ctx)=>ctx.ticker?post.market===ctx.market&&post.ticker===ctx.ticker:post.entityType===ctx.entityType&&post.entityId===ctx.entityId;
  function postHtml(p,likeSet){const url=safeUrl(p.source);return `<article class="rf-post" data-id="${esc(p.id)}"><div class="rf-row"><div class="rf-avatar">${esc((p.author||'익')[0])}</div><div class="rf-body"><div class="rf-meta"><b>${esc(p.author)}</b><span class="rf-badge ${p.stance}">${stanceLabel[p.stance]||'중립'}</span><a class="rf-context" href="${targetUrl(p)}">${esc(p.stockName||p.ticker)} · ${typeLabel[p.entityType]||'토론'}</a><span>· ${ago(p.createdAt)}</span></div><div class="rf-text">${esc(p.text)}</div>${url?`<a class="rf-source-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">근거 링크 열기 ↗</a>`:''}<div class="rf-actions"><button class="rf-like ${likeSet.has(p.id)?'liked':''}">도움됨 ${Number(p.likes)||0}</button><button type="button">답글 ${Number(p.replies)||0}</button><button class="rf-report" type="button">신고</button></div></div></div></article>`;}
  function wirePostActions(root,rerender){root.querySelectorAll('.rf-like').forEach(btn=>btn.onclick=()=>{const id=btn.closest('.rf-post').dataset.id;const posts=read(),set=liked(),post=posts.find(x=>x.id===id);if(!post)return;if(set.has(id)){set.delete(id);post.likes=Math.max(0,(post.likes||0)-1);}else{set.add(id);post.likes=(post.likes||0)+1;}write(posts);localStorage.setItem(LIKES,JSON.stringify([...set]));rerender();});root.querySelectorAll('.rf-report').forEach(btn=>btn.onclick=()=>{btn.textContent='신고 접수됨';btn.disabled=true;});}
  function sentiment(posts){const total=posts.length||1,counts={positive:0,neutral:0,negative:0};posts.forEach(p=>counts[p.stance]=(counts[p.stance]||0)+1);return {counts,pct:k=>Math.round(counts[k]/total*100)};}
  function mount(target,ctx){const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;ctx={market:'kr',entityType:'stock',entityId:'',ticker:'',stockName:'종목',sector:'기타',...ctx};root.style.display='block';root.classList.add('rf-community');let order='latest',stance='neutral';
    function render(){const posts=read().filter(p=>related(p,ctx));posts.sort((a,b)=>order==='helpful'?(b.likes||0)-(a.likes||0):b.createdAt-a.createdAt);const s=sentiment(posts),likeSet=liked();root.innerHTML=`<div class="rf-panel"><div class="rf-head"><h3>💬 ${esc(ctx.stockName)} 토론</h3><span class="rf-count">${posts.length.toLocaleString('ko-KR')}개 의견</span><a class="rf-all" href="community.html?m=${ctx.market}&ticker=${encodeURIComponent(ctx.ticker)}">커뮤니티 전체 →</a></div><div class="rf-sentiment"><div><b style="font-size:12px">의견 분포</b><div class="rf-sbar"><i class="positive" style="width:${s.pct('positive')}%"></i><i class="neutral" style="width:${s.pct('neutral')}%"></i><i class="negative" style="width:${s.pct('negative')}%"></i></div><div class="rf-slabels"><span>긍정 ${s.pct('positive')}%</span><span>중립 ${s.pct('neutral')}%</span><span>부정 ${s.pct('negative')}%</span></div></div><div class="rf-topic"><b>${esc(ctx.ticker||typeLabel[ctx.entityType])}</b>근거 있는 의견을 우선합니다</div></div><div class="rf-compose"><div class="rf-stance">${['positive','neutral','negative'].map(x=>`<button data-stance="${x}" class="${x===stance?'on':''}">${stanceLabel[x]}</button>`).join('')}</div><textarea maxlength="600" placeholder="가격 예측보다 근거와 틀릴 수 있는 조건을 함께 남겨주세요."></textarea><div class="rf-compose-bottom"><input class="rf-source" placeholder="근거 링크 (선택)" inputmode="url"><button class="rf-submit">의견 등록</button></div></div><div class="rf-note">투자 권유·광고·욕설은 숨김 처리될 수 있습니다. 현재 프로토타입에서는 이 브라우저에 저장됩니다.</div><div class="rf-filter"><button data-order="latest" class="${order==='latest'?'on':''}">최신순</button><button data-order="helpful" class="${order==='helpful'?'on':''}">도움순</button></div><div class="rf-list">${posts.length?posts.slice(0,8).map(p=>postHtml(p,likeSet)).join(''):'<div class="rf-empty">첫 번째 근거 있는 의견을 남겨보세요.</div>'}</div></div>`;
      root.querySelectorAll('[data-stance]').forEach(b=>b.onclick=()=>{stance=b.dataset.stance;root.querySelectorAll('[data-stance]').forEach(x=>x.classList.toggle('on',x===b));});root.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{order=b.dataset.order;render();});root.querySelector('.rf-submit').onclick=()=>{const text=root.querySelector('textarea').value.trim(),source=root.querySelector('.rf-source').value.trim();if(text.length<4){root.querySelector('textarea').focus();return;}const posts=read();posts.unshift({id:'u'+Date.now(),market:ctx.market,entityType:ctx.entityType,entityId:ctx.entityId||ctx.ticker,ticker:ctx.ticker,stockName:ctx.stockName,sector:ctx.sector||'기타',stance,author:'익명투자자',text,source:safeUrl(source),createdAt:Date.now(),likes:0,replies:0});write(posts);render();};wirePostActions(root,render);
    }render();
  }
  function mountHub(target,initial={}){const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;root.classList.add('rf-community');let market=initial.market||'all',sector='전체',sort='latest',query=initial.ticker||'',stance='neutral';
    function render(){const all=read(),sectors=['전체',...new Set(all.map(p=>p.sector).filter(Boolean))];let posts=all.filter(p=>(market==='all'||p.market===market)&&(sector==='전체'||p.sector===sector)&&(!query||(p.ticker+' '+p.stockName+' '+p.text).toLowerCase().includes(query.toLowerCase())));posts.sort((a,b)=>sort==='helpful'?(b.likes||0)-(a.likes||0):b.createdAt-a.createdAt);const likeSet=liked();root.innerHTML=`<div class="rf-panel"><div class="rf-head"><h2>커뮤니티 피드</h2><span class="rf-count">${posts.length}개 토론</span></div><div class="rf-compose"><div class="rf-hub-compose-grid"><select class="rf-new-market"><option value="kr">국장</option><option value="us">미장</option></select><input class="rf-new-ticker" maxlength="12" placeholder="종목코드/티커"><input class="rf-new-name" maxlength="30" placeholder="종목명"></div><div class="rf-stance">${['positive','neutral','negative'].map(x=>`<button data-new-stance="${x}" class="${x===stance?'on':''}">${stanceLabel[x]}</button>`).join('')}</div><textarea maxlength="600" placeholder="종목에 대한 근거와 반대 조건을 함께 적어주세요."></textarea><div class="rf-compose-bottom"><input class="rf-source" placeholder="공시·IR·뉴스 등 근거 링크 (선택)"><button class="rf-submit">토론 올리기</button></div></div><div class="rf-hub-toolbar"><input class="rf-search" value="${esc(query)}" placeholder="종목명·티커·내용 검색"><select class="rf-market-filter"><option value="all">전체 시장</option><option value="kr">국장</option><option value="us">미장</option></select><select class="rf-sector-filter">${sectors.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select class="rf-sort"><option value="latest">최신순</option><option value="helpful">도움순</option></select></div><div class="rf-list">${posts.length?posts.map(p=>postHtml(p,likeSet)).join(''):'<div class="rf-empty">조건에 맞는 토론이 없습니다.</div>'}</div></div>`;
      root.querySelector('.rf-market-filter').value=market;root.querySelector('.rf-sector-filter').value=sector;root.querySelector('.rf-sort').value=sort;root.querySelector('.rf-search').oninput=e=>{query=e.target.value;render();};root.querySelector('.rf-market-filter').onchange=e=>{market=e.target.value;render();};root.querySelector('.rf-sector-filter').onchange=e=>{sector=e.target.value;render();};root.querySelector('.rf-sort').onchange=e=>{sort=e.target.value;render();};root.querySelectorAll('[data-new-stance]').forEach(b=>b.onclick=()=>{stance=b.dataset.newStance;root.querySelectorAll('[data-new-stance]').forEach(x=>x.classList.toggle('on',x===b));});root.querySelector('.rf-submit').onclick=()=>{const m=root.querySelector('.rf-new-market').value,ticker=root.querySelector('.rf-new-ticker').value.trim().toUpperCase(),name=root.querySelector('.rf-new-name').value.trim(),text=root.querySelector('textarea').value.trim(),source=root.querySelector('.rf-source').value.trim();if(!ticker){root.querySelector('.rf-new-ticker').focus();return;}if(text.length<4){root.querySelector('textarea').focus();return;}const posts=read();posts.unshift({id:'u'+Date.now(),market:m,entityType:'stock',entityId:ticker,ticker,stockName:name||ticker,sector:'기타',stance,author:'익명투자자',text,source:safeUrl(source),createdAt:Date.now(),likes:0,replies:0});write(posts);market=m;query=ticker;render();};wirePostActions(root,render);
    }render();
  }
  function mountPreview(target,options={}){
    const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;
    const market=['kr','us'].includes(options.market)?options.market:'all';
    const posts=read().filter(p=>market==='all'||p.market===market).sort((a,b)=>(b.likes||0)-(a.likes||0)).slice(0,4);
    root.className='rf-community rf-preview';
    root.innerHTML=`<div class="rf-panel"><div class="rf-head"><div><h2>💬 실시간 커뮤니티</h2><span class="rf-count">${market==='kr'?'국장':market==='us'?'미장':'국장·미장'}에서 근거가 좋은 의견</span></div><a class="rf-all" href="community.html${market==='all'?'':'?m='+market}">전체 토론 보기 →</a></div><div class="rf-preview-grid">${posts.map(p=>`<a class="rf-preview-post" href="${targetUrl(p)}"><div class="rf-preview-top"><span class="rf-market">${p.market==='us'?'미장':'국장'}</span><b>${esc(p.stockName||p.ticker)}</b><span class="rf-badge ${p.stance}">${stanceLabel[p.stance]}</span><span>· ${ago(p.createdAt)}</span></div><div class="rf-preview-text">${esc(p.text)}</div><div class="rf-preview-foot"><span>${esc(p.author)}</span><span>도움됨 ${Number(p.likes)||0} · 답글 ${Number(p.replies)||0}</span></div></a>`).join('')}</div></div>`;
  }
  function simplePostHtml(p,likeSet){
    return `<article class="rf-post" data-id="${esc(p.id)}"><div class="rf-row"><div class="rf-avatar">${esc((p.author||'익')[0])}</div><div class="rf-body"><div class="rf-meta"><b>${esc(p.author)}</b><a class="rf-context" href="${targetUrl(p)}">${esc(p.stockName||p.ticker||'자유토론')}</a><span>· ${ago(p.createdAt)}</span></div>${p.title?`<div class="rf-post-title">${esc(p.title)}</div>`:''}<div class="rf-text">${esc(p.text)}</div><div class="rf-actions"><button class="rf-like ${likeSet.has(p.id)?'liked':''}">공감 ${Number(p.likes)||0}</button><button type="button">댓글 ${Number(p.replies)||0}</button><button class="rf-report" type="button">신고</button></div></div></div></article>`;
  }
  function openEditor(ctx,onSave){
    document.querySelector('.rf-editor-layer')?.remove();
    const layer=document.createElement('div');layer.className='rf-editor-layer';
    layer.innerHTML=`<div class="rf-editor"><div class="rf-editor-nav"><button class="rf-editor-back" aria-label="닫기">‹</button><button class="rf-editor-submit" disabled>남기기</button></div><div class="rf-editor-who"><div class="rf-editor-avatar">익</div><b>익명투자자</b><span>›</span><strong>${esc(ctx.stockName||ctx.ticker||'자유토론')}</strong></div><input class="rf-editor-title" maxlength="80" placeholder="제목을 입력해주세요"><textarea class="rf-editor-content" maxlength="1200" placeholder="내용을 입력해주세요"></textarea><div class="rf-editor-rule"><u>커뮤니티서비스 이용규칙</u> 광고·도배·비방 글을 남기면 활동이 제한될 수 있어요.<b>외부 공유 허용됨</b></div><div class="rf-editor-tools" aria-label="첨부 기능 준비 중"><button type="button" disabled>GIF</button><button type="button" disabled>사진</button><button type="button" disabled>투표</button><button type="button" disabled># 종목태그</button><small>준비 중</small></div></div>`;
    document.body.appendChild(layer);const title=layer.querySelector('.rf-editor-title'),content=layer.querySelector('.rf-editor-content'),submit=layer.querySelector('.rf-editor-submit');
    const validate=()=>{submit.disabled=title.value.trim().length<2||content.value.trim().length<2;};title.oninput=validate;content.oninput=validate;layer.querySelector('.rf-editor-back').onclick=()=>layer.remove();layer.onclick=e=>{if(e.target===layer)layer.remove();};submit.onclick=()=>{if(submit.disabled)return;onSave({title:title.value.trim(),text:content.value.trim()});layer.remove();};setTimeout(()=>title.focus(),0);
  }
  function mountSimple(target,ctx){
    const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;ctx={market:'kr',entityType:'stock',entityId:'',ticker:'',stockName:'종목',sector:'기타',...ctx};root.style.display='block';root.classList.add('rf-community');let order='latest';
    function render(){const posts=read().filter(p=>related(p,ctx)).sort((a,b)=>order==='helpful'?(b.likes||0)-(a.likes||0):b.createdAt-a.createdAt),likeSet=liked();root.innerHTML=`<div class="rf-panel"><div class="rf-head"><h3>💬 ${esc(ctx.stockName)} 커뮤니티</h3><span class="rf-count">${posts.length}개 글</span><a class="rf-all" href="community.html?m=${ctx.market}&ticker=${encodeURIComponent(ctx.ticker)}">전체 보기 →</a></div><button class="rf-write-trigger"><span class="rf-avatar">익</span><span>${esc(ctx.stockName)}에 대해 이야기해보세요</span><b>글쓰기</b></button><div class="rf-filter"><button data-order="latest" class="${order==='latest'?'on':''}">최신순</button><button data-order="helpful" class="${order==='helpful'?'on':''}">공감순</button></div><div class="rf-list">${posts.length?posts.slice(0,8).map(p=>simplePostHtml(p,likeSet)).join(''):'<div class="rf-empty">첫 번째 글을 남겨보세요.</div>'}</div></div>`;root.querySelector('.rf-write-trigger').onclick=()=>openEditor(ctx,data=>{const posts=read();posts.unshift({id:'u'+Date.now(),market:ctx.market,entityType:ctx.entityType,entityId:ctx.entityId||ctx.ticker,ticker:ctx.ticker,stockName:ctx.stockName,sector:ctx.sector||'기타',stance:'neutral',author:'익명투자자',title:data.title,text:data.text,source:'',createdAt:Date.now(),likes:0,replies:0});write(posts);render();});root.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{order=b.dataset.order;render();});wirePostActions(root,render);}
    render();
  }
  function mountHubSimple(target,initial={}){
    const root=typeof target==='string'?document.querySelector(target):target;if(!root)return;root.classList.add('rf-community');let market=initial.market||'all',sector='전체',sort='latest',query=initial.ticker||'';
    function render(){const all=read(),sectors=['전체',...new Set(all.map(p=>p.sector).filter(Boolean))];let posts=all.filter(p=>(market==='all'||p.market===market)&&(sector==='전체'||p.sector===sector)&&(!query||(p.ticker+' '+p.stockName+' '+(p.title||'')+' '+p.text).toLowerCase().includes(query.toLowerCase())));posts.sort((a,b)=>sort==='helpful'?(b.likes||0)-(a.likes||0):b.createdAt-a.createdAt);const likeSet=liked(),editorMarket=market==='all'?'kr':market,editorTicker=initial.ticker||'',editorName=editorTicker||'자유토론';root.innerHTML=`<div class="rf-panel"><div class="rf-head"><h2>커뮤니티 피드</h2><span class="rf-count">${posts.length}개 글</span><button class="rf-hub-write">글쓰기</button></div><div class="rf-hub-toolbar"><input class="rf-search" value="${esc(query)}" placeholder="종목명·티커·내용 검색"><select class="rf-market-filter"><option value="all">전체 시장</option><option value="kr">국장</option><option value="us">미장</option></select><select class="rf-sector-filter">${sectors.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select class="rf-sort"><option value="latest">최신순</option><option value="helpful">공감순</option></select></div><div class="rf-list">${posts.length?posts.map(p=>simplePostHtml(p,likeSet)).join(''):'<div class="rf-empty">조건에 맞는 글이 없습니다.</div>'}</div></div>`;root.querySelector('.rf-market-filter').value=market;root.querySelector('.rf-sector-filter').value=sector;root.querySelector('.rf-sort').value=sort;root.querySelector('.rf-search').oninput=e=>{query=e.target.value;render();};root.querySelector('.rf-market-filter').onchange=e=>{market=e.target.value;render();};root.querySelector('.rf-sector-filter').onchange=e=>{sector=e.target.value;render();};root.querySelector('.rf-sort').onchange=e=>{sort=e.target.value;render();};root.querySelector('.rf-hub-write').onclick=()=>openEditor({market:editorMarket,ticker:editorTicker,stockName:editorName},data=>{const posts=read();posts.unshift({id:'u'+Date.now(),market:editorMarket,entityType:editorTicker?'stock':'general',entityId:editorTicker,ticker:editorTicker,stockName:editorName,sector:'기타',stance:'neutral',author:'익명투자자',title:data.title,text:data.text,source:'',createdAt:Date.now(),likes:0,replies:0});write(posts);render();});wirePostActions(root,render);}
    render();
  }
  window.RichflowCommunity={mount:mountSimple,mountHub:mountHubSimple,mountPreview,read};
})();
