(function(){
  const button=document.getElementById('priceAlertBtn');if(!button)return;
  const market=button.dataset.market||'kr',STORE='richflow:price-alerts:v1';
  const style=document.createElement('style');style.textContent=`.pa-layer{position:fixed;inset:0;z-index:1000;background:rgba(20,23,28,.42);display:flex;align-items:center;justify-content:center;padding:18px}.pa-box{width:min(420px,100%);background:var(--card,#f4f5f7);border:1px solid var(--line,#d3d6dd);border-radius:20px;padding:22px;box-shadow:0 25px 70px rgba(0,0,0,.22);color:var(--txt,#1b1e24)}.pa-head{display:flex;align-items:center;gap:10px}.pa-head h2{font-size:20px}.pa-close{margin-left:auto;border:0;background:transparent;font-size:25px;cursor:pointer}.pa-stock{margin-top:6px;color:var(--txt-3,#68707c);font-size:12px}.pa-current{font-size:28px;font-weight:900;margin:18px 0}.pa-direction{display:grid;grid-template-columns:1fr 1fr;gap:7px}.pa-direction button{border:1px solid var(--line,#d3d6dd);background:var(--card-2,#e9ebef);border-radius:10px;padding:10px;font:inherit;font-size:12px;font-weight:800;cursor:pointer}.pa-direction button.on{background:var(--brand,#434955);border-color:var(--brand,#434955);color:#fff}.pa-field{margin-top:14px}.pa-field label{display:block;font-size:11px;font-weight:800;color:var(--txt-3,#68707c);margin-bottom:6px}.pa-input{display:flex;align-items:center;border:1px solid var(--line,#d3d6dd);background:#fff;border-radius:11px;padding:0 12px}.pa-input input{width:100%;border:0;outline:0;background:transparent;padding:12px 0;font:inherit;font-size:16px;font-weight:800}.pa-input span{font-size:12px;color:var(--txt-3,#68707c)}.pa-preview{background:var(--card-2,#e9ebef);border-radius:11px;padding:12px;margin-top:14px;font-size:12px;line-height:1.5;color:var(--txt-2,#474d58)}.pa-note{font-size:10px;color:var(--txt-3,#68707c);margin-top:10px}.pa-actions{display:flex;gap:8px;margin-top:18px}.pa-actions button{flex:1;border:1px solid var(--line,#d3d6dd);background:var(--card-2,#e9ebef);border-radius:11px;padding:11px;font:inherit;font-size:12px;font-weight:850;cursor:pointer}.pa-actions .pa-save{background:var(--brand,#434955);border-color:var(--brand,#434955);color:#fff}.pa-actions .pa-delete{color:#d8455a}.icon-btn.pa-on{background:var(--brand,#434955)!important;color:#fff!important;border-color:var(--brand,#434955)!important}.pa-toast{position:fixed;left:50%;bottom:28px;z-index:1100;transform:translateX(-50%);background:#1b1e24;color:#fff;padding:11px 16px;border-radius:11px;font-size:12px;font-weight:800;box-shadow:0 8px 30px rgba(0,0,0,.2)}@media(max-width:520px){.pa-layer{align-items:flex-end;padding:0}.pa-box{border-radius:20px 20px 0 0}}`;document.head.appendChild(style);
  const read=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{};}catch(e){return {};}};
  const write=value=>localStorage.setItem(STORE,JSON.stringify(value));
  const ticker=()=>{const value=(document.getElementById('shCode')?.textContent||'').split(/[ ·]/)[0].toUpperCase();return market==='us'?(/^[A-Z.\-]{1,12}$/.test(value)?value:''):(/^[0-9A-Z]{6}$/.test(value)?value:'');};
  const stockName=()=>{const el=document.getElementById('shName');return el?.childNodes?.[0]?.textContent?.trim()||ticker();};
  const price=()=>Number(String(document.getElementById('shPx')?.textContent||'').replace(/[^0-9.\-]/g,''))||0;
  const ready=()=>!!ticker()&&price()>0;
  const key=()=>market+':'+ticker();
  const format=value=>market==='us'?'$'+Number(value).toLocaleString('en-US',{maximumFractionDigits:2}):Number(value).toLocaleString('ko-KR')+'원';
  const toast=text=>{document.querySelector('.pa-toast')?.remove();const el=document.createElement('div');el.className='pa-toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2600);};
  function updateButton(){const isReady=ready();button.disabled=!isReady;button.style.opacity=isReady?'':'0.45';button.style.cursor=isReady?'pointer':'wait';button.classList.toggle('pa-on',isReady&&!!read()[key()]);button.title=isReady?(read()[key()]?'가격 알림 설정됨':'가격 알림 설정'):'종목 시세를 불러오는 중입니다';}
  function open(){if(!ready()){toast('종목 시세를 불러온 뒤 설정할 수 있어요');updateButton();return;}document.querySelector('.pa-layer')?.remove();let direction='below';const current=price(),saved=read()[key()];if(saved)direction=saved.direction;const layer=document.createElement('div');layer.className='pa-layer';layer.innerHTML=`<div class="pa-box"><div class="pa-head"><span>🔔</span><h2>가격 알림</h2><button class="pa-close">×</button></div><div class="pa-stock">${stockName()} · ${ticker()}</div><div class="pa-current">${format(current)}</div><div class="pa-direction"><button data-dir="below">내려가면 알림</button><button data-dir="above">올라가면 알림</button></div><div class="pa-field"><label>목표 가격</label><div class="pa-input"><input class="pa-target" inputmode="decimal" placeholder="가격 입력"><span>${market==='us'?'USD':'원'}</span></div></div><div class="pa-field"><label>현재가 대비 등락률</label><div class="pa-input"><input class="pa-percent" inputmode="decimal" placeholder="예: 5"><span>%</span></div></div><div class="pa-preview"></div><div class="pa-note">페이지가 열려 있는 동안 가격을 확인해 알립니다.</div><div class="pa-actions">${saved?'<button class="pa-delete">알림 해제</button>':''}<button class="pa-save">저장</button></div></div>`;document.body.appendChild(layer);const target=layer.querySelector('.pa-target'),percent=layer.querySelector('.pa-percent'),preview=layer.querySelector('.pa-preview');if(saved){target.value=saved.target||'';percent.value=saved.percent||'';}
    const sync=source=>{let t=Number(target.value),p=Math.abs(Number(percent.value));if(current){if(source==='percent'&&p)t=current*(direction==='below'?1-p/100:1+p/100),target.value=(market==='us'?t.toFixed(2):Math.round(t));else if(source==='target'&&t)p=Math.abs((t/current-1)*100),percent.value=p?p.toFixed(2):'';}preview.textContent=t?`${format(t)} ${direction==='below'?'이하':'이상'}가 되면 알려드려요${p?' · 현재가 대비 '+p.toFixed(2)+'%':''}`:'목표 가격이나 등락률을 입력해주세요.';};
    layer.querySelectorAll('[data-dir]').forEach(b=>{b.classList.toggle('on',b.dataset.dir===direction);b.onclick=()=>{direction=b.dataset.dir;layer.querySelectorAll('[data-dir]').forEach(x=>x.classList.toggle('on',x===b));sync('percent');};});target.oninput=()=>sync('target');percent.oninput=()=>sync('percent');sync();layer.querySelector('.pa-close').onclick=()=>layer.remove();layer.onclick=e=>{if(e.target===layer)layer.remove();};layer.querySelector('.pa-save').onclick=async()=>{if(!ready()){layer.remove();updateButton();toast('종목 시세를 다시 확인해주세요');return;}const t=Number(target.value),p=Math.abs(Number(percent.value));if(!t&&!p){target.focus();return;}const all=read();all[key()]={market,ticker:ticker(),name:stockName(),basePrice:current,direction,target:t||0,percent:p||0,createdAt:Date.now(),notified:false};write(all);updateButton();layer.remove();toast('가격 알림이 저장됐어요');if('Notification'in window&&Notification.permission==='default')try{await Notification.requestPermission();}catch(e){}};layer.querySelector('.pa-delete')?.addEventListener('click',()=>{const all=read();delete all[key()];write(all);updateButton();layer.remove();toast('가격 알림을 해제했어요');});
  }
  function check(){const alert=read()[key()],current=price();if(!alert||!current||alert.notified)return;const pct=alert.basePrice?Math.abs((current/alert.basePrice-1)*100):0;const hit=alert.direction==='below'?((alert.target&&current<=alert.target)||(alert.percent&&current<=alert.basePrice*(1-alert.percent/100))):((alert.target&&current>=alert.target)||(alert.percent&&current>=alert.basePrice*(1+alert.percent/100)));if(!hit)return;const all=read();all[key()].notified=true;write(all);const message=`${stockName()} ${format(current)} · 설정한 ${pct.toFixed(2)}% 조건 도달`;toast(message);if('Notification'in window&&Notification.permission==='granted')new Notification('RICHFLOW 가격 알림',{body:message});}
  button.onclick=open;new MutationObserver(()=>{updateButton();check();}).observe(document.getElementById('shPx'),{childList:true,subtree:true,characterData:true});new MutationObserver(updateButton).observe(document.getElementById('shCode'),{childList:true,subtree:true,characterData:true});updateButton();
})();
